# Generated by Django 5.2.10 on 2026-01-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_can_collect_cash_user_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_stock',
            field=models.BooleanField(default=False),
        ),
    ]
