# Generated by Django 5.2.10 on 2026-01-26 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_qr_secret'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_collect_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('restaurant_owner', 'Restaurant Owner'), ('staff', 'Restaurant Staff')], default='restaurant_owner', max_length=20),
        ),
    ]
