# Generated by Django 5.2.10 on 2026-01-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_can_manage_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_manage_stock',
        ),
    ]
