# Generated by Django 5.2.10 on 2026-01-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_qr_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_manage_stock',
            field=models.BooleanField(default=False, help_text='Allow staff to update item availability and stock quantities'),
        ),
    ]
