# Generated by Django 5.2.10 on 2026-01-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_auditl_restaur_idx_core_auditl_restaur_818ea8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Changed'), ('ORDER_CREATED', 'Order Created'), ('ORDER_STATUS_CHANGE', 'Order Status Changed'), ('ORDER_COMPLETED', 'Order Completed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('CASH_COLLECTED', 'Cash Collected'), ('REFUND_ISSUED', 'Refund Issued'), ('STAFF_CREATED', 'Staff Created'), ('STAFF_UPDATED', 'Staff Updated'), ('STAFF_PERMISSION_CHANGE', 'Staff Permission Changed'), ('STAFF_DEACTIVATED', 'Staff Deactivated'), ('RESTAURANT_CREATED', 'Restaurant Created'), ('RESTAURANT_UPDATED', 'Restaurant Updated'), ('RESTAURANT_STATUS_CHANGE', 'Restaurant Status Changed'), ('SUBSCRIPTION_CANCELLED', 'Subscription Cancelled'), ('SUBSCRIPTION_REACTIVATED', 'Subscription Reactivated'), ('QR_REGENERATED', 'QR Code Regenerated'), ('QR_SCANNED', 'QR Code Scanned'), ('QR_VERIFIED', 'QR Verification Successful'), ('QR_VERIFICATION_FAILED', 'QR Verification Failed'), ('MENU_ITEM_CREATED', 'Menu Item Created'), ('MENU_ITEM_UPDATED', 'Menu Item Updated'), ('MENU_ITEM_DELETED', 'Menu Item Deleted'), ('CATEGORY_CREATED', 'Category Created'), ('CATEGORY_DELETED', 'Category Deleted')], db_index=True, max_length=50),
        ),
    ]
