# Generated by Django 6.0.1 on 2026-01-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_analytics_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
    ]
