# Generated by Django 5.2.10 on 2026-01-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_add_payment_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='orders_paym_restaur_ab3968_idx',
            old_name='orders_paym_restaur_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='orders_paym_order_i_8c8d98_idx',
            old_name='orders_paym_order_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='orders_paym_status_83f434_idx',
            old_name='orders_paym_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='orders_paym_externa_549d50_idx',
            old_name='orders_paym_external_idx',
        ),
    ]
