# Generated by Django 5.2.10 on 2026-01-30 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_orders_paym_restaur_idx_orders_paym_restaur_ab3968_idx_and_more'),
        ('restaurants', '0004_staff_can_manage_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('items', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('expired', 'Expired')], default='active', max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('table_number', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(max_length=10)),
                ('is_parcel', models.BooleanField(default=False)),
                ('spicy_level', models.CharField(default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
    ]
