# Generated by Django 5.2.10 on 2026-01-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='qr_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
