# Generated by Django 6.0.1 on 2026-01-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_restaur_818ea8_idx',
            old_name='core_auditl_restaur_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_user_id_7b678c_idx',
            old_name='core_auditl_user_ti_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_096de0_idx',
            old_name='core_auditl_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_entity__244637_idx',
            old_name='core_auditl_entity_idx',
        ),
    ]
