# Generated by Django 5.2.10 on 2026-01-25 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
        ('restaurants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CASH_COLLECTED', 'Cash Collected'), ('CASH_ORDER_CREATED', 'Cash Order Created'), ('CASH_REFUND', 'Cash Refund'), ('PAYMENT_OVERRIDE', 'Payment Override')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cash Audit Log',
                'verbose_name_plural': 'Cash Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cash_collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_collected_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_collected_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='hour_of_day',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'hour_of_day'], name='orders_orde_restaur_4e20e6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'day_of_week'], name='orders_orde_restaur_22bd61_idx'),
        ),
        migrations.AddField(
            model_name='cashauditlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_audit_logs', to='orders.order'),
        ),
        migrations.AddField(
            model_name='cashauditlog',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_audit_logs', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='cashauditlog',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cashauditlog',
            index=models.Index(fields=['restaurant', 'created_at'], name='orders_cash_restaur_8666a8_idx'),
        ),
        migrations.AddIndex(
            model_name='cashauditlog',
            index=models.Index(fields=['staff', 'created_at'], name='orders_cash_staff_i_8f6697_idx'),
        ),
        migrations.AddIndex(
            model_name='cashauditlog',
            index=models.Index(fields=['order'], name='orders_cash_order_i_76ec4c_idx'),
        ),
    ]
