# Generated by Django 5.2.10 on 2026-01-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_add_menuitemattribute'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menuitemattribute',
            name='unique_menu_item_attribute_name',
        ),
        migrations.RenameIndex(
            model_name='menuitemattribute',
            new_name='menu_menuit_restaur_e183a3_idx',
            old_name='menu_menuitemattr_rest_item_idx',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_vegetarian',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemattribute',
            unique_together={('menu_item', 'name')},
        ),
    ]
