# Generated by Django 5.2.10 on 2026-01-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_stock_quantity_menuitem_unavailable_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='unavailable_reason',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='unavailable_since',
        ),
    ]
