# Generated by Django 5.2.10 on 2026-01-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_menuitem_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Current stock quantity. NULL means unlimited stock.', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='unavailable_reason',
            field=models.CharField(blank=True, default='', help_text='Reason why item is unavailable (e.g., "Out of stock", "Seasonal")', max_length=255),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='unavailable_since',
            field=models.DateTimeField(blank=True, help_text='When the item became unavailable', null=True),
        ),
    ]
