# Generated by Django 5.2.10 on 2026-01-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menuitem_stock_quantity_menuitem_unavailable_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock currently reserved in pending orders.'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Total physical stock. NULL means unlimited stock.', null=True),
        ),
    ]
