# Generated by Django 5.2.10 on 2026-01-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_change_vegetarian_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.IntegerField(blank=True, help_text='Null for unlimited, 0 for out of stock', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='unavailable_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='unavailable_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
